name-template: $NEXT_MINOR_VERSION
tag-template: v$NEXT_MINOR_VERSION

categories:
  - title: 🚀 New features and improvements
    labels:
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - bug
  - title: 🚦 Internal changes
    labels:
      - internal

exclude-labels:
  - no-changelog
  - duplicate
  - invalid

template: |
  $CHANGES
