build:
  verbosity: detailed

build_script:
  - cmd: .\gradlew.bat assemble --no-daemon

test_script:
  - cmd: .\gradlew.bat check --no-daemon

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk11

skip_commits:
  files:
    - README*
    - .travis.yml

on_success:
  - cmd: if exist "%USERPROFILE%\.gradle\caches\modules-2\modules-2.lock" del /Q "%USERPROFILE%\.gradle\caches\modules-2\modules-2.lock"
  - cmd: for /D %%d in ("%USERPROFILE%\.gradle\caches\*") do if exist "%%d\plugin-resolution" rmdir /S /Q "%%d\plugin-resolution"
cache:
  - '%USERPROFILE%\.gradle\caches -> build.gradle.kts'
  - '%USERPROFILE%\.gradle\wrapper -> gradle\wrapper\gradle-wrapper.properties'
