name: Checks
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - '*'

env:
  LANG: "en_US.UTF-8"
  LC_MESSAGES: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"
  LANGUAGE: "en_US:en"
  GRADLE_OPTS: >-
    -Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false

jobs:
  gradle:
    runs-on: macOS-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache Gradle Caches
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: cache-clean-gradle-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: cache-clean-wrapper-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Chmod permissions
        run: sudo chmod +x ./gradlew

      - name: Run detekt
        run: ./gradlew detektAll

      - name: Run build
        run: ./gradlew clean spotlessApply build --warning-mode all

      # We stop gradle at the end to make sure the cache folders
      # don't contain any lock files and are free to be cached.
      - name: Stop Gradle
        run: ./gradlew --stop
