name: Validate Gradle wrapper

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - '*'

jobs:
  validation:
    name: Validation
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 2

      - name: Prepare git
        run: |
          git config --global core.autocrlf false
          git config --global core.ignorecase false
          git config --global help.autocorrect 1
          git config --global core.fileMode false

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
