name: Greetings

on:
  issues:
  # Remove PRs from dependabot
  pull_request:
    branches:
      - '!dependabot/*'

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Thank you for creating an issue; one of our team members will get back to you soon!'
          pr-message: >-
            Hey contributor! Thank you creating a PR.

            If there's anything we can do to help, please don't hesitate to reach out to us at GitHub (https://github.com/AlexRogalskiy/gradle-java-sample).

            Thanks again!
