name: Test

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Chmod permissions
        run: sudo chmod +x ./gradlew

      - name: Test
        run: ./gradlew test -i
